// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4p3Vutyv9pVddwsU2nIAiCi1l9MX45OI',
    appId: '1:339537085581:web:dc272eb44d4ffe1eb00ec4',
    messagingSenderId: '339537085581',
    projectId: 'screener-boursier',
    authDomain: 'screener-boursier.firebaseapp.com',
    storageBucket: 'screener-boursier.firebasestorage.app',
    measurementId: 'G-906MDYW96Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOSpMbZKtAYealNjr-BlUI3-I0q3tXzo',
    appId: '1:339537085581:android:813748662c1191a7b00ec4',
    messagingSenderId: '339537085581',
    projectId: 'screener-boursier',
    storageBucket: 'screener-boursier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuynit9YeaGY_f_8zpT9sNvPq72NXegYg',
    appId: '1:339537085581:ios:929caeb1168f0b25b00ec4',
    messagingSenderId: '339537085581',
    projectId: 'screener-boursier',
    storageBucket: 'screener-boursier.firebasestorage.app',
    iosBundleId: 'com.example.screenerBoursier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuynit9YeaGY_f_8zpT9sNvPq72NXegYg',
    appId: '1:339537085581:ios:929caeb1168f0b25b00ec4',
    messagingSenderId: '339537085581',
    projectId: 'screener-boursier',
    storageBucket: 'screener-boursier.firebasestorage.app',
    iosBundleId: 'com.example.screenerBoursier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4p3Vutyv9pVddwsU2nIAiCi1l9MX45OI',
    appId: '1:339537085581:web:a9542d4a28c05982b00ec4',
    messagingSenderId: '339537085581',
    projectId: 'screener-boursier',
    authDomain: 'screener-boursier.firebaseapp.com',
    storageBucket: 'screener-boursier.firebasestorage.app',
    measurementId: 'G-JTVEX9RN3P',
  );
}
